CREATE TABLE Departments(
    Dept_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Dept_name VARCHAR2(100) NOT NULL UNIQUE
);

CREATE TABLE Room(
    Room_no INT PRIMARY KEY,
    Cost INT
);

CREATE TABLE Doctors(
    Doctor_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY, 
    First_name VARCHAR2(50) NOT NULL,
    Last_name VARCHAR2(50) NOT NULL,
    Dept_id INT REFERENCES Departments(Dept_id),
    Qualification VARCHAR2(200),
    Email VARCHAR2(100)
);

CREATE TABLE Patients(
    Patient_id INT GENERATED BY DEFAULT as IDENTITY PRIMARY KEY,
    First_name VARCHAR2(100),
    Last_name VARCHAR2(100),
    Age INT,
    Gender CHAR(1) CHECK(Gender IN('M', 'F')),
    Email VARCHAR2(100) UNIQUE,
    Passwords VARCHAR2(100),
    Address VARCHAR2(200)
);

CREATE TABLE Appoint(
    Appoint_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Patient_id INT REFERENCES Patients(Patient_id) ON DELETE CASCADE,
    Doctor_id INT REFERENCES Doctors(Doctor_id) ON DELETE CASCADE,
    DateOfVisit DATE
);

CREATE TABLE Admit(
    Admit_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Patient_id INT REFERENCES Patients(Patient_id),
    Doctor_id INT REFERENCES Doctors(Doctor_id),
    AdmmitDate DATE,
    ReleaseeDate DATE,
    Room_no INT REFERENCES Room(Room_no)
);

CREATE TABLE Tests (
    Test_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Test_name VARCHAR2(100),
    Test_cost INT
);

CREATE TABLE Surgeries (
    Surgery_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Surgery_name VARCHAR2(100),
    Surgery_cost INT
);

CREATE TABLE Patient_Tests (
    Patient_Test_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Patient_id INT REFERENCES Patients(Patient_id),
    Test_id INT REFERENCES Tests(Test_id),
    Test_date DATE
);

CREATE TABLE Patient_Surgeries (
    Patient_Surgery_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Patient_id INT REFERENCES Patients(Patient_id),
    Surgery_id INT REFERENCES Surgeries(Surgery_id),
    Surgery_date DATE
);

CREATE TABLE Patient_Bills (
    Bill_id INT GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) PRIMARY KEY,
    Patient_id INT REFERENCES Patients(Patient_id),
    Cost INT,
    Bill_date DATE
);

commit;






